# Generated by tools/generate_struggle_configs.py -- do not edit by hand.
# task_generalization: taskgen_tangram_task04
_base_ = ["../../re2tal/e2e_struggle_resize_re2tal_actionformer_slowfast101.py"]

annotation_path = "../data/EvoStruggle/splits/indomain_generalization/Tangram/Tangram_subactivity04_data.json"
data_path = "../data/EvoStruggle/data/360p/Tangram"

dataset = dict(
    train=dict(ann_file=annotation_path, data_path=data_path, subset_name=['train']),
    val=dict(ann_file=annotation_path, data_path=data_path, subset_name=['validation']),
    test=dict(ann_file=annotation_path, data_path=data_path, subset_name=['test']),
)

evaluation = dict(subset=['test'], ground_truth_filename=annotation_path)

work_dir = "exps/struggle/taskgen_tangram_task04"
