# Generated by tools/generate_struggle_configs.py -- do not edit by hand.
# activity_generalization: activitygen_origami
_base_ = ["../../re2tal/e2e_struggle_re2tal_actionformer_slowfast101.py"]

annotation_path = "../data/EvoStruggle/splits/crossdomain_generalization/Origami/Origami_crossdomain_testonvalonly.json"
data_path = "../data/EvoStruggle/data/360p"

dataset = dict(
    train=dict(ann_file=annotation_path, data_path=data_path, subset_name=['train']),
    val=dict(ann_file=annotation_path, data_path=data_path, subset_name=['validation']),
    test=dict(ann_file=annotation_path, data_path=data_path, subset_name=['test']),
)

evaluation = dict(subset=['test'], ground_truth_filename=annotation_path)

work_dir = "exps/struggle/activitygen_origami"
