# Generated by tools/generate_struggle_configs.py -- do not edit by hand.
# within_activity: within_tangram
_base_ = ["../../re2tal/e2e_struggle_resize_re2tal_actionformer_slowfast101.py"]

annotation_path = "../data/EvoStruggle/splits/separate_attempts/Tangram/Tangram_sepattempt.json"
data_path = "../data/EvoStruggle/data/360p/Tangram"

dataset = dict(
    train=dict(ann_file=annotation_path, data_path=data_path, subset_name=['train_attempt01', 'train_attempt02', 'train_attempt03', 'train_attempt04', 'train_attempt05']),
    val=dict(ann_file=annotation_path, data_path=data_path, subset_name=['validation']),
    test=dict(ann_file=annotation_path, data_path=data_path, subset_name=['validation']),
)

evaluation = dict(subset=['validation'], ground_truth_filename=annotation_path)

work_dir = "exps/struggle/within_tangram"
