"""Generate one config file per EvoStruggle experiment.

The configs are derived from the original configs used for the paper:

- actionformer_release/configs/struggle_slowfast{,_combined}.yaml
- TriDet/configs/struggle_slowfast{,_combined}.yaml
- OpenTAD/configs/re2tal/e2e_struggle_re2tal_actionformer_slowfast101.py

Only the dataset paths and the train/val/test subsets are changed; all other
settings (model, optimizer, schedule, ...) are copied verbatim.

Usage (from the root of the repository):
    python tools/generate_struggle_configs.py
"""
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
# paths are relative to the codebase directory (e.g. actionformer_release/)
DATA_ROOT = '../data/EvoStruggle'

# (directory name in EvoStruggle, short name used in file names, task ids)
ACTIVITIES = [
    ('Tying_Knots', 'tyingknots', [1, 2, 3, 4, 5]),
    ('Origami', 'origami', [1, 2, 3, 4]),
    ('Tangram', 'tangram', [1, 2, 3, 4]),
    ('Shuffle_Cards', 'shufflecards', [1, 2, 3, 4, 5]),
]
ALL_ATTEMPTS = ['train_attempt{:02d}'.format(i) for i in range(1, 6)]


def experiments():
    """Yield (setting, name, combined, json_file, activity, train, val, test)."""
    for act, short, tasks in ACTIVITIES:
        sep = f'splits/separate_attempts/{act}/{act}_sepattempt.json'
        # Within-Activity (Table 2): train on all attempts, report on validation
        yield ('within_activity', f'within_{short}', False, sep, act,
               ALL_ATTEMPTS, ['validation'], ['validation'])
        # Separate attempts (Fig. 9): train on a single attempt, report on validation
        for i, attempt in enumerate(ALL_ATTEMPTS, 1):
            yield ('separate_attempts', f'sepattempt_{short}_attempt{i:02d}', False, sep, act,
                   [attempt], ['validation'], ['validation'])
        # All attempts sampled to the size of one attempt (supplementary material)
        for s in (1, 2, 3):
            js = f'splits/separate_attempts/{act}/{act}_allattempts_sample{s:02d}.json'
            yield ('allattempts_sampled', f'allattempts_{short}_sample{s:02d}', False, js, act,
                   ['train'], ['validation'], ['validation'])
        # Task-level generalization (Table 3): select the model on validation (tasks seen in
        # training, other participants), report on the held-out task
        for t in tasks:
            js = f'splits/indomain_generalization/{act}/{act}_subactivity{t:02d}_data.json'
            yield ('task_generalization', f'taskgen_{short}_task{t:02d}', False, js, act,
                   ['train'], ['validation'], ['test'])
        # Activity-level generalization (Table 4, Fig. 6): train on the train sets of the other three
        # activities, select the model on their validation sets, report on the validation set of
        # the held-out activity (subset `test` in the *_testonvalonly.json files)
        js = f'splits/crossdomain_generalization/{act}/{act}_crossdomain_testonvalonly.json'
        yield ('activity_generalization', f'activitygen_{short}', True, js, None,
               ['train'], ['validation'], ['test'])


def set_yaml_field(text, key, value):
    """Replace the (first, uncommented) line `key: ...` keeping its indentation."""
    pattern = re.compile(r'^(\s*)' + re.escape(key) + r':.*$', re.MULTILINE)
    assert pattern.search(text), key
    return pattern.sub(lambda m: f'{m.group(1)}{key}: {value}', text, count=1)


def make_yaml(base_text, json_file, feat_folder, train, val):
    # drop the commented-out alternatives of json_file / feat_folder
    text = re.sub(r'^\s*#\s*(json_file|feat_folder):.*\n', '', base_text, flags=re.MULTILINE)
    text = set_yaml_field(text, 'train_split', str(train))
    text = set_yaml_field(text, 'val_split', str(val))
    text = set_yaml_field(text, 'json_file', f'{DATA_ROOT}/{json_file},')
    text = set_yaml_field(text, 'feat_folder', f'{feat_folder},')
    return text


OPENTAD_TEMPLATE = '''# Generated by tools/generate_struggle_configs.py -- do not edit by hand.
# {setting}: {name}
_base_ = ["../../re2tal/e2e_struggle_re2tal_actionformer_slowfast101.py"]

annotation_path = "{ann}"
data_path = "{data_path}"

dataset = dict(
    train=dict(ann_file=annotation_path, data_path=data_path, subset_name={train}),
    val=dict(ann_file=annotation_path, data_path=data_path, subset_name={val}),
    test=dict(ann_file=annotation_path, data_path=data_path, subset_name={test}),
)

evaluation = dict(subset={test}, ground_truth_filename=annotation_path)

work_dir = "exps/struggle/{name}"
'''


def main():
    header = '# Generated by tools/generate_struggle_configs.py -- do not edit by hand.\n'
    bases = {}
    for codebase in ('actionformer_release', 'TriDet'):
        for combined in (False, True):
            fn = 'struggle_slowfast_combined.yaml' if combined else 'struggle_slowfast.yaml'
            with open(os.path.join(REPO_ROOT, codebase, 'configs', fn)) as f:
                bases[codebase, combined] = f.read()

    n = 0
    for setting, name, combined, json_file, act, train, val, test in experiments():
        feats = f'{DATA_ROOT}/extracted_features/slowfast_features'
        videos = f'{DATA_ROOT}/data/360p'
        if act is not None:
            feats, videos = f'{feats}/{act}', f'{videos}/{act}'

        # ActionFormer / TriDet: trainval.py keeps the checkpoint with the best mAP on
        # val_split (the validation subset); if the results are reported on another subset,
        # evaluate the selected checkpoint with `eval.py <config> <ckpt> --split <subset>`
        for codebase in ('actionformer_release', 'TriDet'):
            out_dir = os.path.join(REPO_ROOT, codebase, 'configs', 'struggle', setting)
            os.makedirs(out_dir, exist_ok=True)
            note = header
            if test != val:
                note += (f'# Model selection on {val}; report results on {test} with:\n'
                         f'#   python eval.py <this config> <ckpt folder> --split {" ".join(test)}\n')
            text = note + make_yaml(bases[codebase, combined], json_file, feats, train, val)
            with open(os.path.join(out_dir, name + '.yaml'), 'w') as f:
                f.write(text)
            n += 1

        # OpenTAD (Re2TAL) was used for Within-Activity, Task and Activity generalization
        if setting in ('within_activity', 'task_generalization', 'activity_generalization'):
            out_dir = os.path.join(REPO_ROOT, 'OpenTAD', 'configs', 'struggle', setting)
            os.makedirs(out_dir, exist_ok=True)
            with open(os.path.join(out_dir, name + '.py'), 'w') as f:
                f.write(OPENTAD_TEMPLATE.format(
                    setting=setting, name=name, ann=f'{DATA_ROOT}/{json_file}',
                    data_path=videos, train=train, val=val, test=test))
            n += 1
    print(f'Generated {n} config files.')


if __name__ == '__main__':
    main()
